name: navigation
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  main_page:
    path: ../features/main_page

  auto_route: ^9.3.0+1

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: ^2.4.15
  auto_route_generator: ^9.3.1
